$axure.loadCurrentPage({
  "url":"查询实验.html",
  "generationDate":new Date(1557073067448.87),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3883c42996784454bd99a0ca0dbb8a83",
    "type":"Axure:Page",
    "name":"查询实验",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a176d348d6e0490a856f3f778783ecce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":20,
              "y":10},
            "size":{
              "width":156,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0a0a075c8a046b789d6be3bd542f69b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":20,
                  "y":10},
                "size":{
                  "width":156,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb34ec1518464cdb9eedb22939c513e7",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":130},
            "size":{
              "width":343,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88cf8e1ea29e4ed0bddce43eb89cfc91",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"66b2d6d0978a4f47834fdc290017f797",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"1033c222cbc9472fae1a6ff243fb5ad6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"56a6be996bef4ca6859030ff616f6aef",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"3b377c0897e84a82a57995cb07c7acc8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"436b22a77cbe483eae0b4b2a1914a39c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"e3ec2ad5f4374ea59025ab4f1a2de059",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ac0dce57727546168458f2e97b32e579",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"bbaa134bf6c4442f9bd96139ca05f592",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b19610379fef45fab71bd3ffb43056a3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"fe958d24a4f046e3957afecf0ca4cd55",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"643711a4ddc74063897a6863fe0f8f9a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"6a03926953ca4d0397c46fa2be5721a9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":143,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"32671a1ff72d44d59d36244ddf2a95f0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":143,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询实验/u7.png"}},
{
              "id":"cea3a5e5fbcd467ea1e29d9873667e27",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":143,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8e5944f8810343e78d1ba18781ae77e5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":143,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询实验/u7.png"}},
{
              "id":"1deaa855335242ad96bf0263f273b2de",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":143,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"49c317e27f8148988cdb7d6af36159b5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":143,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询实验/u7.png"}},
{
              "id":"99b8b4f3c8264826ac0ae6fd9db2d443",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c1e61f9cd0c740fe873ccf759d918660",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u74.png"}},
{
              "id":"067425677bb1414fbffb6739edccf0c8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7f8498fa716a4bfc9d97e5d889978d35",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u74.png"}},
{
              "id":"b0f99ec4b42e46bba009260b80671d62",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":90},
                "size":{
                  "width":143,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d3df9198ae854a77bf165224651a43ce",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":90},
                    "size":{
                      "width":143,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询实验/u25.png"}}]},
{
          "id":"96971c62d8814903b4ce71bb5fda921e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":50},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83212da511864e8baa30bce975fb0fa2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":50},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ca744b12fbd45ef9c6a8bec52f70d8f",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":57,
              "y":50},
            "size":{
              "width":153,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"f8b9e9eaa1ac41328dbc71632b612cdb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":90},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c4145ba3ea040fcb2ea087468b658fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":90},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"87bdb489358b4634beb388db82f5f78c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":165},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"61c9e7ee7b664d2196e587252dd749b6",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":190},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5ed442d82a1b4cffa14bf6bd519c5e34",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":190},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5efef03f9e4440848c0447e1932bc863",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":225},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"00469e1f030348a8859bbee6b9665b24",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":225},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "a176d348d6e0490a856f3f778783ecce":{
      "scriptId":"u0"},
    "a0a0a075c8a046b789d6be3bd542f69b":{
      "scriptId":"u1"},
    "cb34ec1518464cdb9eedb22939c513e7":{
      "scriptId":"u2"},
    "88cf8e1ea29e4ed0bddce43eb89cfc91":{
      "scriptId":"u3"},
    "66b2d6d0978a4f47834fdc290017f797":{
      "scriptId":"u4"},
    "e3ec2ad5f4374ea59025ab4f1a2de059":{
      "scriptId":"u5"},
    "ac0dce57727546168458f2e97b32e579":{
      "scriptId":"u6"},
    "6a03926953ca4d0397c46fa2be5721a9":{
      "scriptId":"u7"},
    "32671a1ff72d44d59d36244ddf2a95f0":{
      "scriptId":"u8"},
    "1033c222cbc9472fae1a6ff243fb5ad6":{
      "scriptId":"u9"},
    "56a6be996bef4ca6859030ff616f6aef":{
      "scriptId":"u10"},
    "bbaa134bf6c4442f9bd96139ca05f592":{
      "scriptId":"u11"},
    "b19610379fef45fab71bd3ffb43056a3":{
      "scriptId":"u12"},
    "cea3a5e5fbcd467ea1e29d9873667e27":{
      "scriptId":"u13"},
    "8e5944f8810343e78d1ba18781ae77e5":{
      "scriptId":"u14"},
    "3b377c0897e84a82a57995cb07c7acc8":{
      "scriptId":"u15"},
    "436b22a77cbe483eae0b4b2a1914a39c":{
      "scriptId":"u16"},
    "fe958d24a4f046e3957afecf0ca4cd55":{
      "scriptId":"u17"},
    "643711a4ddc74063897a6863fe0f8f9a":{
      "scriptId":"u18"},
    "1deaa855335242ad96bf0263f273b2de":{
      "scriptId":"u19"},
    "49c317e27f8148988cdb7d6af36159b5":{
      "scriptId":"u20"},
    "99b8b4f3c8264826ac0ae6fd9db2d443":{
      "scriptId":"u21"},
    "c1e61f9cd0c740fe873ccf759d918660":{
      "scriptId":"u22"},
    "067425677bb1414fbffb6739edccf0c8":{
      "scriptId":"u23"},
    "7f8498fa716a4bfc9d97e5d889978d35":{
      "scriptId":"u24"},
    "b0f99ec4b42e46bba009260b80671d62":{
      "scriptId":"u25"},
    "d3df9198ae854a77bf165224651a43ce":{
      "scriptId":"u26"},
    "96971c62d8814903b4ce71bb5fda921e":{
      "scriptId":"u27"},
    "83212da511864e8baa30bce975fb0fa2":{
      "scriptId":"u28"},
    "1ca744b12fbd45ef9c6a8bec52f70d8f":{
      "scriptId":"u29"},
    "f8b9e9eaa1ac41328dbc71632b612cdb":{
      "scriptId":"u30"},
    "5c4145ba3ea040fcb2ea087468b658fa":{
      "scriptId":"u31"},
    "87bdb489358b4634beb388db82f5f78c":{
      "scriptId":"u32"},
    "61c9e7ee7b664d2196e587252dd749b6":{
      "scriptId":"u33"},
    "5ed442d82a1b4cffa14bf6bd519c5e34":{
      "scriptId":"u34"},
    "5efef03f9e4440848c0447e1932bc863":{
      "scriptId":"u35"},
    "00469e1f030348a8859bbee6b9665b24":{
      "scriptId":"u36"}}});