$axure.loadCurrentPage({
  "url":"增加实验.html",
  "generationDate":new Date(1557073067638.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"28122ed588294d78b1d01cf4cc73348f",
    "type":"Axure:Page",
    "name":"增加实验",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2243558c89224753a7c2a25959c0754b",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "size":{
              "width":510,
              "height":420}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bee10e7999de4380854954b4a1cb1200",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":510,
                  "height":420}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加实验/u0.png"}},
{
          "id":"16f3cf274e1646d99ea83736f619d87f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":155,
              "y":20},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d6a2b31219394a61b3df6e37329313d8",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":110,
              "y":85},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ba16ecd50dc74906a7e2985204eee96e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":280,
              "y":85},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9ab29729d97945bd8b64ffc660bbbc87",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":110,
              "y":130},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6c095a63b1d349098737aff2e71947c6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":280,
              "y":130},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ee58dae4c8cd4b86b4f89cda7a751c58",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":180},
            "size":{
              "width":300,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a911433a623749c7af581a7117513855",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b4700618a2554117a9b66d5a35e3306e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"bc37f5cff0724aa3997727b283f1bfb9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cb79172d156f44339ef1ea7a40f0d272",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"61194e04022c4cb8b492391f0467d287",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f246695795ee47ba974db48ef1eb535d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"ea7d90b65c25428681f97b7326ef7e24",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b47cb50cc61147768a1037f75fb679e9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"5d37f3138e22446e9cd8e83e4e7661bc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9ebd22c14a7f4b448bf9019c64a91a75",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"26abaca33c574c1f8f2a9a6340171691",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"97a9eddef7da4ecaa12e6f525fba1dc2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"17027cd541c546ac90ba1f236b12685b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"56485b3768b946e2932787a602e3463e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u54.png"}},
{
              "id":"81980f81958e42d2b4515237dbcdc10f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"97ba68e354454104ba6f9396a453f4cf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u54.png"}},
{
              "id":"f54597a991be455ab4b894833d8ca19b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"342b9333e65c4b20ad363aa78f2c3d3f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u54.png"}},
{
              "id":"f6d6c0fe2591437996368ed3e36154da",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3964f98430fd41fbba6e30216cd96e14",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u74.png"}},
{
              "id":"2badce91d30c4a16881c57676d730971",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"79d41317e23444fca8c81e3982208004",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u74.png"}},
{
              "id":"4bc43f84c794445b8a55a29f4cadaf7d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"114a454ddcc043ab92f275fba5fd8bdc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u90.png"}},
{
              "id":"f2656249e40c4b55bba431c462dd3e01",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"87dd6221eec94967adc9619b30ee8c29",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"14d2b34af9f245c48c0ef938934b453b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b111d97e9bbc4bd087e50758e620b0c3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"c570f70ca39d451bbc45b9a3ab8d16a8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"47d5d20fc4314877866842d41e81b369",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u54.png"}}]},
{
          "id":"698881d65373449783d8c5d7c4b3ec75",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":305,
              "y":220},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"84119ab0826b42ba98df065f5588eead",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":305,
              "y":245},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a56d44c1d6474976a5865d10f6732b31",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":305,
              "y":270},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"10a3a9b83b4349b296494b58f6837d34",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":305,
              "y":305},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2b2f512fef2a49eb8c302bc5ccebb0ff",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":355},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查询实验",
                      "target":{
                        "targetType":"page",
                        "url":"查询实验.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"dd9f4497d28044aab6ef792a5f55be6c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":355},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 学生列表",
                      "target":{
                        "targetType":"page",
                        "url":"学生列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "2243558c89224753a7c2a25959c0754b":{
      "scriptId":"u0"},
    "bee10e7999de4380854954b4a1cb1200":{
      "scriptId":"u1"},
    "16f3cf274e1646d99ea83736f619d87f":{
      "scriptId":"u2"},
    "d6a2b31219394a61b3df6e37329313d8":{
      "scriptId":"u3"},
    "ba16ecd50dc74906a7e2985204eee96e":{
      "scriptId":"u4"},
    "9ab29729d97945bd8b64ffc660bbbc87":{
      "scriptId":"u5"},
    "6c095a63b1d349098737aff2e71947c6":{
      "scriptId":"u6"},
    "ee58dae4c8cd4b86b4f89cda7a751c58":{
      "scriptId":"u7"},
    "a911433a623749c7af581a7117513855":{
      "scriptId":"u8"},
    "b4700618a2554117a9b66d5a35e3306e":{
      "scriptId":"u9"},
    "ea7d90b65c25428681f97b7326ef7e24":{
      "scriptId":"u10"},
    "b47cb50cc61147768a1037f75fb679e9":{
      "scriptId":"u11"},
    "17027cd541c546ac90ba1f236b12685b":{
      "scriptId":"u12"},
    "56485b3768b946e2932787a602e3463e":{
      "scriptId":"u13"},
    "bc37f5cff0724aa3997727b283f1bfb9":{
      "scriptId":"u14"},
    "cb79172d156f44339ef1ea7a40f0d272":{
      "scriptId":"u15"},
    "5d37f3138e22446e9cd8e83e4e7661bc":{
      "scriptId":"u16"},
    "9ebd22c14a7f4b448bf9019c64a91a75":{
      "scriptId":"u17"},
    "81980f81958e42d2b4515237dbcdc10f":{
      "scriptId":"u18"},
    "97ba68e354454104ba6f9396a453f4cf":{
      "scriptId":"u19"},
    "61194e04022c4cb8b492391f0467d287":{
      "scriptId":"u20"},
    "f246695795ee47ba974db48ef1eb535d":{
      "scriptId":"u21"},
    "26abaca33c574c1f8f2a9a6340171691":{
      "scriptId":"u22"},
    "97a9eddef7da4ecaa12e6f525fba1dc2":{
      "scriptId":"u23"},
    "f54597a991be455ab4b894833d8ca19b":{
      "scriptId":"u24"},
    "342b9333e65c4b20ad363aa78f2c3d3f":{
      "scriptId":"u25"},
    "f2656249e40c4b55bba431c462dd3e01":{
      "scriptId":"u26"},
    "87dd6221eec94967adc9619b30ee8c29":{
      "scriptId":"u27"},
    "14d2b34af9f245c48c0ef938934b453b":{
      "scriptId":"u28"},
    "b111d97e9bbc4bd087e50758e620b0c3":{
      "scriptId":"u29"},
    "c570f70ca39d451bbc45b9a3ab8d16a8":{
      "scriptId":"u30"},
    "47d5d20fc4314877866842d41e81b369":{
      "scriptId":"u31"},
    "f6d6c0fe2591437996368ed3e36154da":{
      "scriptId":"u32"},
    "3964f98430fd41fbba6e30216cd96e14":{
      "scriptId":"u33"},
    "2badce91d30c4a16881c57676d730971":{
      "scriptId":"u34"},
    "79d41317e23444fca8c81e3982208004":{
      "scriptId":"u35"},
    "4bc43f84c794445b8a55a29f4cadaf7d":{
      "scriptId":"u36"},
    "114a454ddcc043ab92f275fba5fd8bdc":{
      "scriptId":"u37"},
    "698881d65373449783d8c5d7c4b3ec75":{
      "scriptId":"u38"},
    "84119ab0826b42ba98df065f5588eead":{
      "scriptId":"u39"},
    "a56d44c1d6474976a5865d10f6732b31":{
      "scriptId":"u40"},
    "10a3a9b83b4349b296494b58f6837d34":{
      "scriptId":"u41"},
    "2b2f512fef2a49eb8c302bc5ccebb0ff":{
      "scriptId":"u42"},
    "dd9f4497d28044aab6ef792a5f55be6c":{
      "scriptId":"u43"}}});