$axure.loadCurrentPage({
  "url":"删除实验.html",
  "generationDate":new Date(1557073067672.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fa73ab6b97684b54b5680ddf6186ccc0",
    "type":"Axure:Page",
    "name":"删除实验",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0b1d561bdfc54a91b42f5942f5ec3d43",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":20,
              "y":10},
            "size":{
              "width":156,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"698917a492a6415589f1cbd51c0390e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":20,
                  "y":10},
                "size":{
                  "width":156,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"120e7feacee447b79dfaa63d49f37f2d",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":130},
            "size":{
              "width":343,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c079b90f034a499985a3f8aa80b7d228",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"297407aa0ed6452daa889570e8269427",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"bf85a96525cb4a80802b103907daa66b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"180351debed645ce934760c111412ab9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"9ec20068f9884bde96076f52e9d7a4d4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f8b1ef8b89f547efa4b148bfbae8ceb5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"096eea08903147ba98934d911f023390",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1dcca5b67d0f4f9fa3a596199c32c272",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"48694b3c356c4929aadde9d5f6c9e9ef",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d67a209e3f424b888ca3d75fcac138e9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"6d9d87addb764e2c9dc2c494f82b36f5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7ffab50ef929450392bbaef6196eb65d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"eb5b5f65a0bf439fa6c06c265032e655",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":143,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3095ce393c114831ab7c55dc51e1bcfd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":143,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询实验/u7.png"}},
{
              "id":"596398e7d3d8443b8c29f055eaeb1623",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":143,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"06a65d5ebc3b438e9760e54450e25ad1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":143,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询实验/u7.png"}},
{
              "id":"4739cfcfc23547d39d5f9ea544f9cc76",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":143,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9d57a1a13d3c4c69be5c07ae821655f7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":143,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询实验/u7.png"}},
{
              "id":"76f5710c44b74e4793a9809dc2ae8059",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"82fb467b1a794023a2335d6196032024",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u74.png"}},
{
              "id":"724704dcf61a4afe91af35963ae8d160",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5fcaf964aea14483b8caa5354f438b9e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u74.png"}},
{
              "id":"ab9a109dbd0d4e6ba1c42b07e098d5f0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":90},
                "size":{
                  "width":143,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0fd603546b59477a9d195366a75123d5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":90},
                    "size":{
                      "width":143,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询实验/u25.png"}}]},
{
          "id":"fda34ab18ea04c95a01274fd377cc1b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":50},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9eea7041284a4419be6b4f6c6962b902",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":50},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1f8f22556fe438d86f2cbac6609b55b",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":57,
              "y":50},
            "size":{
              "width":153,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"30a9405269394b8f8053ae280ffa2916",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":90},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2064c2842324b8b8c27ca9a9d1bf2da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":90},
                "size":{
                  "width":90,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e928f5245e94273bb7505399f253e3d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":165},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b6ac0c998f594c59a2afcf41b481d0fd",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":190},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c2a7a5d3b08b49fda9db9a99db5f459f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":190},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"712e0122fcd64df8b3df927aacdb86d9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":225},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"935987902f404788a7498c3e28137437",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":225},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "0b1d561bdfc54a91b42f5942f5ec3d43":{
      "scriptId":"u0"},
    "698917a492a6415589f1cbd51c0390e8":{
      "scriptId":"u1"},
    "120e7feacee447b79dfaa63d49f37f2d":{
      "scriptId":"u2"},
    "c079b90f034a499985a3f8aa80b7d228":{
      "scriptId":"u3"},
    "297407aa0ed6452daa889570e8269427":{
      "scriptId":"u4"},
    "096eea08903147ba98934d911f023390":{
      "scriptId":"u5"},
    "1dcca5b67d0f4f9fa3a596199c32c272":{
      "scriptId":"u6"},
    "eb5b5f65a0bf439fa6c06c265032e655":{
      "scriptId":"u7"},
    "3095ce393c114831ab7c55dc51e1bcfd":{
      "scriptId":"u8"},
    "bf85a96525cb4a80802b103907daa66b":{
      "scriptId":"u9"},
    "180351debed645ce934760c111412ab9":{
      "scriptId":"u10"},
    "48694b3c356c4929aadde9d5f6c9e9ef":{
      "scriptId":"u11"},
    "d67a209e3f424b888ca3d75fcac138e9":{
      "scriptId":"u12"},
    "596398e7d3d8443b8c29f055eaeb1623":{
      "scriptId":"u13"},
    "06a65d5ebc3b438e9760e54450e25ad1":{
      "scriptId":"u14"},
    "9ec20068f9884bde96076f52e9d7a4d4":{
      "scriptId":"u15"},
    "f8b1ef8b89f547efa4b148bfbae8ceb5":{
      "scriptId":"u16"},
    "6d9d87addb764e2c9dc2c494f82b36f5":{
      "scriptId":"u17"},
    "7ffab50ef929450392bbaef6196eb65d":{
      "scriptId":"u18"},
    "4739cfcfc23547d39d5f9ea544f9cc76":{
      "scriptId":"u19"},
    "9d57a1a13d3c4c69be5c07ae821655f7":{
      "scriptId":"u20"},
    "76f5710c44b74e4793a9809dc2ae8059":{
      "scriptId":"u21"},
    "82fb467b1a794023a2335d6196032024":{
      "scriptId":"u22"},
    "724704dcf61a4afe91af35963ae8d160":{
      "scriptId":"u23"},
    "5fcaf964aea14483b8caa5354f438b9e":{
      "scriptId":"u24"},
    "ab9a109dbd0d4e6ba1c42b07e098d5f0":{
      "scriptId":"u25"},
    "0fd603546b59477a9d195366a75123d5":{
      "scriptId":"u26"},
    "fda34ab18ea04c95a01274fd377cc1b8":{
      "scriptId":"u27"},
    "9eea7041284a4419be6b4f6c6962b902":{
      "scriptId":"u28"},
    "a1f8f22556fe438d86f2cbac6609b55b":{
      "scriptId":"u29"},
    "30a9405269394b8f8053ae280ffa2916":{
      "scriptId":"u30"},
    "d2064c2842324b8b8c27ca9a9d1bf2da":{
      "scriptId":"u31"},
    "0e928f5245e94273bb7505399f253e3d":{
      "scriptId":"u32"},
    "b6ac0c998f594c59a2afcf41b481d0fd":{
      "scriptId":"u33"},
    "c2a7a5d3b08b49fda9db9a99db5f459f":{
      "scriptId":"u34"},
    "712e0122fcd64df8b3df927aacdb86d9":{
      "scriptId":"u35"},
    "935987902f404788a7498c3e28137437":{
      "scriptId":"u36"}}});