$axure.loadCurrentPage({
  "url":"删除课程.html",
  "generationDate":new Date(1557073067583.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1b42168c75b14595a1326f2195877390",
    "type":"Axure:Page",
    "name":"删除课程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9f3cff9786f146618a9bd29be94f7f09",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":45},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9347518df23445528480d2c24624d945",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":45},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b63f1331ff01478da6df7253c2917abf",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":100},
            "size":{
              "width":427,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"370b8e051f6447b5a3370705e9658a6f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":107,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7f1300f64182475b8e0af4b2f1e7e113",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":107,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询课程/u3.png"}},
{
              "id":"71d7f306c28e4caabb0442f821e880f4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":107,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6a39ef5b0d1942e99ad663413128f4a3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":107,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询课程/u3.png"}},
{
              "id":"fe8f86b42faa42ee99db0e4f7c79b1a3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":107,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bbb648eba723424695c0ff307a503f99",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":107,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询课程/u19.png"}},
{
              "id":"8a04ef75872e404694b24fb7bb476ec3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":107,
                  "y":0},
                "size":{
                  "width":107,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"41b1abcb2a274d86ba8d8168c17e321c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":107,
                      "y":0},
                    "size":{
                      "width":107,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询课程/u3.png"}},
{
              "id":"12c17cfc1b19461bb4d8c9ee27aa000b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":107,
                  "y":30},
                "size":{
                  "width":107,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"84aa6f9b0e0c4639815b06057a641b24",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":107,
                      "y":30},
                    "size":{
                      "width":107,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询课程/u3.png"}},
{
              "id":"3ff5b8f760e7456fa09da9cfec32592e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":107,
                  "y":60},
                "size":{
                  "width":107,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"123974bff3ec464a9d3fdd57b6e7ed71",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":107,
                      "y":60},
                    "size":{
                      "width":107,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询课程/u19.png"}},
{
              "id":"004d888650cb46789202c46cb3f208d4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":214,
                  "y":0},
                "size":{
                  "width":107,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0786d5d3df2243f8a56b25c576d0054c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":214,
                      "y":0},
                    "size":{
                      "width":107,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询课程/u3.png"}},
{
              "id":"21ee4b08334346bd946eba37cc994177",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":214,
                  "y":30},
                "size":{
                  "width":107,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0e73e66cf6364c599cab8942ecef3f1e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":214,
                      "y":30},
                    "size":{
                      "width":107,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询课程/u3.png"}},
{
              "id":"5866772e68a64626b922b861f44696f7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":214,
                  "y":60},
                "size":{
                  "width":107,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0107a42148c2402cb8792cd7968cd15e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":214,
                      "y":60},
                    "size":{
                      "width":107,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询课程/u19.png"}},
{
              "id":"02efc4f9979142e7b0c461014aa1499a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":321,
                  "y":0},
                "size":{
                  "width":106,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"16834001382e4d8881f20554973c0fa3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":321,
                      "y":0},
                    "size":{
                      "width":106,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询课程/u9.png"}},
{
              "id":"51abf3997af94c63b17ec5c253a2e508",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":321,
                  "y":30},
                "size":{
                  "width":106,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e1dd8c045a324229995d7167232d45a4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":321,
                      "y":30},
                    "size":{
                      "width":106,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询课程/u9.png"}},
{
              "id":"79e73eb8e5b345189e90f9014468ec8a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":321,
                  "y":60},
                "size":{
                  "width":106,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"664b69ac89c74cc183ad89bbd683f55b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":321,
                      "y":60},
                    "size":{
                      "width":106,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询课程/u25.png"}}]},
{
          "id":"3e18492cf9754919a62e99cb292aead4",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":377,
              "y":132},
            "size":{
              "width":93,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "9f3cff9786f146618a9bd29be94f7f09":{
      "scriptId":"u0"},
    "9347518df23445528480d2c24624d945":{
      "scriptId":"u1"},
    "b63f1331ff01478da6df7253c2917abf":{
      "scriptId":"u2"},
    "370b8e051f6447b5a3370705e9658a6f":{
      "scriptId":"u3"},
    "7f1300f64182475b8e0af4b2f1e7e113":{
      "scriptId":"u4"},
    "8a04ef75872e404694b24fb7bb476ec3":{
      "scriptId":"u5"},
    "41b1abcb2a274d86ba8d8168c17e321c":{
      "scriptId":"u6"},
    "004d888650cb46789202c46cb3f208d4":{
      "scriptId":"u7"},
    "0786d5d3df2243f8a56b25c576d0054c":{
      "scriptId":"u8"},
    "02efc4f9979142e7b0c461014aa1499a":{
      "scriptId":"u9"},
    "16834001382e4d8881f20554973c0fa3":{
      "scriptId":"u10"},
    "71d7f306c28e4caabb0442f821e880f4":{
      "scriptId":"u11"},
    "6a39ef5b0d1942e99ad663413128f4a3":{
      "scriptId":"u12"},
    "12c17cfc1b19461bb4d8c9ee27aa000b":{
      "scriptId":"u13"},
    "84aa6f9b0e0c4639815b06057a641b24":{
      "scriptId":"u14"},
    "21ee4b08334346bd946eba37cc994177":{
      "scriptId":"u15"},
    "0e73e66cf6364c599cab8942ecef3f1e":{
      "scriptId":"u16"},
    "51abf3997af94c63b17ec5c253a2e508":{
      "scriptId":"u17"},
    "e1dd8c045a324229995d7167232d45a4":{
      "scriptId":"u18"},
    "fe8f86b42faa42ee99db0e4f7c79b1a3":{
      "scriptId":"u19"},
    "bbb648eba723424695c0ff307a503f99":{
      "scriptId":"u20"},
    "3ff5b8f760e7456fa09da9cfec32592e":{
      "scriptId":"u21"},
    "123974bff3ec464a9d3fdd57b6e7ed71":{
      "scriptId":"u22"},
    "5866772e68a64626b922b861f44696f7":{
      "scriptId":"u23"},
    "0107a42148c2402cb8792cd7968cd15e":{
      "scriptId":"u24"},
    "79e73eb8e5b345189e90f9014468ec8a":{
      "scriptId":"u25"},
    "664b69ac89c74cc183ad89bbd683f55b":{
      "scriptId":"u26"},
    "3e18492cf9754919a62e99cb292aead4":{
      "scriptId":"u27"}}});