$axure.loadCurrentPage({
  "url":"编辑实验信息.html",
  "generationDate":new Date(1557073067724.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"057e494b396546eba45023273e03fe4c",
    "type":"Axure:Page",
    "name":"编辑实验信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"74a5b693bbf04c84a869cfb69e58ef72",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "size":{
              "width":510,
              "height":420}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9939f34a0b0a4140a6d71f0d2b4a2d05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":510,
                  "height":420}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加实验/u0.png"}},
{
          "id":"27f79868f64442ba9859538caad64970",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":155,
              "y":20},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a64308b2a7ad4c3ba7bee7af61374835",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":110,
              "y":85},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"86349dd9fec6431a888c1a85855e1f79",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":280,
              "y":85},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d70eb5e96751473b85b0648a7f67e0a9",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":110,
              "y":130},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d67857ad93dd4ceea0852dab17e6d61c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":280,
              "y":130},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0571e3cc41c64d37b81c1393173d052a",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":180},
            "size":{
              "width":300,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cce58d8a325046bab9f564b2c3a7e688",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cc9c5b0c64f64f8c9292f1c4c820ba28",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"b2f09045e2ce4b4799e8a374f5539e48",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e6a342046f6b4c76a36e78c8cfa959ce",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"a01a0f950c90459fbf91762b15baa85f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f5dbb6d2cbd64d5298837f378f17a6ac",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"6562abaec82b43e1a3dae326246d50a3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c2abd179a8f147c78b19c0040e9a4705",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"bea37a13e0384bd4aafd5d108be5879f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7e0a5fe0e83a4878a42310aec56cc9e9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"df9086a8fce44066a531bbf88e27a3cf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"234ee77a7c6341ac91696e6c88fea995",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"827006562e3e4e0a987a473242f39c52",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"61d2375a9ed6485889bf34cd77c503f5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u54.png"}},
{
              "id":"b82a5b012dbd4fc49e822e5642cce089",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6acdbd7bd63940e8b977699bdcd9ba8c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u54.png"}},
{
              "id":"db1ba80c19cd41f5b89561a4e71892f8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5330fedec3944ba5bdf726ab87e5d2c6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u54.png"}},
{
              "id":"f8c789d05de742f49abcbc4a6ce9c053",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"571bf018ce5d481f9e0dd2302cdb04a0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u74.png"}},
{
              "id":"1db643b545c74b99881cdea951a1aff5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"68b9325eb1084591a98e874b1eeef4e9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u74.png"}},
{
              "id":"081f0fee03794fae9d19dac85248d17c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d00b2d1bb3294794a3ea6d6847688d4a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u90.png"}},
{
              "id":"a5bef686acae425aa2b780d412d0896a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3eaf3b2206d3470c8eca1524dc6d4269",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"fbea518bab2049bb84f9d0f7a5128a3b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"73e5784bb54948deb5728057d6260844",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"042db0d4680b48ef9b3a1427e5505307",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"81eb0dcf63504c65bc00789cf5b3db63",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u54.png"}}]},
{
          "id":"3eeda9d973b94859aeac545ec0058ccd",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":305,
              "y":220},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2a9a783b5ece417f91e28e243f89c381",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":305,
              "y":245},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"fde980e7f1a44e29956ce7d7c0eedd59",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":305,
              "y":270},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c4e1b5db5b6744cabb3d4553f778e506",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":305,
              "y":305},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1c4e29a091e14a51a9a418a8b09241f4",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":355},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查询实验",
                      "target":{
                        "targetType":"page",
                        "url":"查询实验.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e5e57ed1408348c1bdc6516e1a0c19df",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":355},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 学生列表",
                      "target":{
                        "targetType":"page",
                        "url":"学生列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "74a5b693bbf04c84a869cfb69e58ef72":{
      "scriptId":"u0"},
    "9939f34a0b0a4140a6d71f0d2b4a2d05":{
      "scriptId":"u1"},
    "27f79868f64442ba9859538caad64970":{
      "scriptId":"u2"},
    "a64308b2a7ad4c3ba7bee7af61374835":{
      "scriptId":"u3"},
    "86349dd9fec6431a888c1a85855e1f79":{
      "scriptId":"u4"},
    "d70eb5e96751473b85b0648a7f67e0a9":{
      "scriptId":"u5"},
    "d67857ad93dd4ceea0852dab17e6d61c":{
      "scriptId":"u6"},
    "0571e3cc41c64d37b81c1393173d052a":{
      "scriptId":"u7"},
    "cce58d8a325046bab9f564b2c3a7e688":{
      "scriptId":"u8"},
    "cc9c5b0c64f64f8c9292f1c4c820ba28":{
      "scriptId":"u9"},
    "6562abaec82b43e1a3dae326246d50a3":{
      "scriptId":"u10"},
    "c2abd179a8f147c78b19c0040e9a4705":{
      "scriptId":"u11"},
    "827006562e3e4e0a987a473242f39c52":{
      "scriptId":"u12"},
    "61d2375a9ed6485889bf34cd77c503f5":{
      "scriptId":"u13"},
    "b2f09045e2ce4b4799e8a374f5539e48":{
      "scriptId":"u14"},
    "e6a342046f6b4c76a36e78c8cfa959ce":{
      "scriptId":"u15"},
    "bea37a13e0384bd4aafd5d108be5879f":{
      "scriptId":"u16"},
    "7e0a5fe0e83a4878a42310aec56cc9e9":{
      "scriptId":"u17"},
    "b82a5b012dbd4fc49e822e5642cce089":{
      "scriptId":"u18"},
    "6acdbd7bd63940e8b977699bdcd9ba8c":{
      "scriptId":"u19"},
    "a01a0f950c90459fbf91762b15baa85f":{
      "scriptId":"u20"},
    "f5dbb6d2cbd64d5298837f378f17a6ac":{
      "scriptId":"u21"},
    "df9086a8fce44066a531bbf88e27a3cf":{
      "scriptId":"u22"},
    "234ee77a7c6341ac91696e6c88fea995":{
      "scriptId":"u23"},
    "db1ba80c19cd41f5b89561a4e71892f8":{
      "scriptId":"u24"},
    "5330fedec3944ba5bdf726ab87e5d2c6":{
      "scriptId":"u25"},
    "a5bef686acae425aa2b780d412d0896a":{
      "scriptId":"u26"},
    "3eaf3b2206d3470c8eca1524dc6d4269":{
      "scriptId":"u27"},
    "fbea518bab2049bb84f9d0f7a5128a3b":{
      "scriptId":"u28"},
    "73e5784bb54948deb5728057d6260844":{
      "scriptId":"u29"},
    "042db0d4680b48ef9b3a1427e5505307":{
      "scriptId":"u30"},
    "81eb0dcf63504c65bc00789cf5b3db63":{
      "scriptId":"u31"},
    "f8c789d05de742f49abcbc4a6ce9c053":{
      "scriptId":"u32"},
    "571bf018ce5d481f9e0dd2302cdb04a0":{
      "scriptId":"u33"},
    "1db643b545c74b99881cdea951a1aff5":{
      "scriptId":"u34"},
    "68b9325eb1084591a98e874b1eeef4e9":{
      "scriptId":"u35"},
    "081f0fee03794fae9d19dac85248d17c":{
      "scriptId":"u36"},
    "d00b2d1bb3294794a3ea6d6847688d4a":{
      "scriptId":"u37"},
    "3eeda9d973b94859aeac545ec0058ccd":{
      "scriptId":"u38"},
    "2a9a783b5ece417f91e28e243f89c381":{
      "scriptId":"u39"},
    "fde980e7f1a44e29956ce7d7c0eedd59":{
      "scriptId":"u40"},
    "c4e1b5db5b6744cabb3d4553f778e506":{
      "scriptId":"u41"},
    "1c4e29a091e14a51a9a418a8b09241f4":{
      "scriptId":"u42"},
    "e5e57ed1408348c1bdc6516e1a0c19df":{
      "scriptId":"u43"}}});