$axure.loadCurrentPage({
  "url":"查看成绩.html",
  "generationDate":new Date(1557073067529.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1836e016093843f4b18e2567d2ec29e8",
    "type":"Axure:Page",
    "name":"查看成绩",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"83825c45f122459b82222c6d1054cc3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":50},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b71e7090451842dd9a3c6db5ccb9c668",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":50},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee2bb5678c844314be9523cdbf51da40",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":57,
              "y":50},
            "size":{
              "width":153,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"2a51b62a165545b4955b7fb351ad946e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":50},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5323f4408d294927bb81bc1b928aeab7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":50},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03378b8cad0d4814a0fbcc58fa122a10",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":50},
            "size":{
              "width":153,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"b8c2500f3b834881a5a14a0fcea0b1da",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":90},
            "size":{
              "width":600,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec921a92f4ca4fbaa8a9c39149bfd8d7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"048bb8f76ac24212881e8543a1dc7d99",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"b0072b37f5b041af800193f1e9ac4b90",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4ffc493fdbea4a0d879d0a250af5750c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"4e3a9b7dc1544c0c9e068863e8c43916",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"02fdd70ff16f4eedabc1183fa039071b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"d30d743c33c74e76a31de3275547736c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e41a1754ed5747a2a7e5b21de1d40718",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"6ba6cdd61948445e939cda554993d7ac",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cf6fde0668ce407e8965f9f798542264",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"4d7dd8e64ba243a5b0acbeabd69963ff",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4096ffe763e8448da76948ab70b875fc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"4b3ec7a635444c71a22025be21f43350",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"476833d998644ed19dc2d2bc8ec0a373",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"35c6696d9ce6418481114bda63de00be",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"88e86a1c0b5840caad5aefc4a35ba6b3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"c12ad243293148938dd56d5706d78667",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"64bdecc007ba47fb84e71dac8cf38870",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"95d006a7b23b4c269a57d2617a204677",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"793b27b633ad41fcb442a403060a33d6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"fc42210b9f5a4b7da0aeec540f34637f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0627808ad76d446898935ce53c5589b7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"352da32e965648fca3a02efa6d1b2dd7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6c9c1e2bade546b29189dea86ef6c06c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"4d7d5e6d9fc04fdb8c77e742b482287f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"487656bc358d44379575a37160766c92",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"ff5d739592ff4aeda4ed7b89491f5279",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"979acd319d9d4f67b204e7b8cb470366",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"1908a25357d44cd7aedcc57bd049be7b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9351fbe455e34740853c7ecdb1d6de01",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u38.png"}},
{
              "id":"7617a2e67ee241b9a2d332c89c8299bf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d50bee15887548ce8ff8d53f89e2b1a1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u74.png"}},
{
              "id":"34e288323c1c49538306c53d4ed3325b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5d734e7e70dd4a3e9a5dfa7b7550d512",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u74.png"}},
{
              "id":"e2ec5f44be4d43049589eee5a9f5060f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1f8eadadfa17462a950aa370917b02df",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u74.png"}},
{
              "id":"62675e2f1d1d425f909f0a29612096fc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b19ce1f5cf684068b9d43b9314131fe9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u74.png"}},
{
              "id":"d061b0cea7fc401ba8113f7619616399",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"84781a8beae542c8a0f809219112e9db",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u74.png"}},
{
              "id":"cd0499a919044b01bbe1b09c1c4fe6f9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"273aea964b604b4e827b28c584589292",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u54.png"}},
{
              "id":"bb8c202c5c164a0180ebbd54bac502db",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"20227359175349e0bfc5c6a1eaf10534",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u54.png"}},
{
              "id":"59d9b65d1b2b4d988fa5c795d2b9659c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"88b98d09526d418b8bb652d8696bfed4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u54.png"}},
{
              "id":"c7cb933f5b0544d9ae8854d3394cca38",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"627fd09969cd4cbeb3835ba2ba264b74",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u90.png"}}]},
{
          "id":"7a84777daf4b4529be092e8e1d5a5d2e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":125},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"096a1a16dd9e4507bb39f309d28e09a2",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":150},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b9f2fbb038c5457e8577e1bf17ae1ac6",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":185},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"823b9d2ab3d84140a2bf353342e3e496",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":270},
            "size":{
              "width":580,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fe3392b840a422f8185f6dcb0ef65c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":270},
                "size":{
                  "width":580,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看成绩/u58.png"}},
{
          "id":"129d5ce9ecbe47c3a47308aedf9b2828",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":220,
              "y":296},
            "size":{
              "width":200,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"b24d26c84ac64170a0527998d7f68fe2",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":57,
              "y":340},
            "size":{
              "width":517,
              "height":77}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6968194a270e4424a97adbef6488df81",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":103,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a62d84b278734b1499f72d0e439e461d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":103,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看成绩/u62.png"}},
{
              "id":"46c52d1cb5cc4c06a43bd788c76eb083",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":103,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d929b1497c3d4d0aa6d78c5aaf8f9c7f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":103,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看成绩/u72.png"}},
{
              "id":"2cff92ad80ae4d3c94dfb4a7b7faf50f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":103,
                  "y":0},
                "size":{
                  "width":103,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aec54004202a41118f880e800514e1ef",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":103,
                      "y":0},
                    "size":{
                      "width":103,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看成绩/u62.png"}},
{
              "id":"313d9739689a4dde9e51908a4e328d14",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":103,
                  "y":30},
                "size":{
                  "width":103,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5ce33147497943d2a9d7303da49c6e9e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":103,
                      "y":30},
                    "size":{
                      "width":103,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看成绩/u72.png"}},
{
              "id":"9302e0696812472ea2f3b052f8b81cac",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":206,
                  "y":0},
                "size":{
                  "width":103,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"31d9af566f954ca192c3232d008f0c22",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":206,
                      "y":0},
                    "size":{
                      "width":103,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看成绩/u62.png"}},
{
              "id":"ee85ff8543174ee48758a4bdc9aa8357",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":206,
                  "y":30},
                "size":{
                  "width":103,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"196ea582bc7743c6bf15590219dbe04c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":206,
                      "y":30},
                    "size":{
                      "width":103,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看成绩/u72.png"}},
{
              "id":"ba795135fc3b43aabd0c7c32bbf720fd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":309,
                  "y":0},
                "size":{
                  "width":103,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b33f0c31044a4e028be0b44f0d053ca9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":309,
                      "y":0},
                    "size":{
                      "width":103,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看成绩/u62.png"}},
{
              "id":"e14319f9f3924bef9ff20d8dc3947e6c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":309,
                  "y":30},
                "size":{
                  "width":103,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3af36ddc7cd747259198af9cb60a654e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":309,
                      "y":30},
                    "size":{
                      "width":103,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看成绩/u72.png"}},
{
              "id":"055b8c1723c14fc59814583dee3c709c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":412,
                  "y":0},
                "size":{
                  "width":105,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"31caffc739a84d369be6991d61138a5e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":412,
                      "y":0},
                    "size":{
                      "width":105,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选择课程/u52.png"}},
{
              "id":"1f6d4371a836401684d992c24db8e393",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":412,
                  "y":30},
                "size":{
                  "width":105,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9ee35a07ac8c43d9947e96fa15565a1a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":412,
                      "y":30},
                    "size":{
                      "width":105,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看成绩/u80.png"}}]},
{
          "id":"9c342e96ca4e435786a3911c819fb0c0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":50.5,
              "y":417},
            "size":{
              "width":530,
              "height":70}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "83825c45f122459b82222c6d1054cc3e":{
      "scriptId":"u0"},
    "b71e7090451842dd9a3c6db5ccb9c668":{
      "scriptId":"u1"},
    "ee2bb5678c844314be9523cdbf51da40":{
      "scriptId":"u2"},
    "2a51b62a165545b4955b7fb351ad946e":{
      "scriptId":"u3"},
    "5323f4408d294927bb81bc1b928aeab7":{
      "scriptId":"u4"},
    "03378b8cad0d4814a0fbcc58fa122a10":{
      "scriptId":"u5"},
    "b8c2500f3b834881a5a14a0fcea0b1da":{
      "scriptId":"u6"},
    "ec921a92f4ca4fbaa8a9c39149bfd8d7":{
      "scriptId":"u7"},
    "048bb8f76ac24212881e8543a1dc7d99":{
      "scriptId":"u8"},
    "d30d743c33c74e76a31de3275547736c":{
      "scriptId":"u9"},
    "e41a1754ed5747a2a7e5b21de1d40718":{
      "scriptId":"u10"},
    "4b3ec7a635444c71a22025be21f43350":{
      "scriptId":"u11"},
    "476833d998644ed19dc2d2bc8ec0a373":{
      "scriptId":"u12"},
    "4d7d5e6d9fc04fdb8c77e742b482287f":{
      "scriptId":"u13"},
    "487656bc358d44379575a37160766c92":{
      "scriptId":"u14"},
    "95d006a7b23b4c269a57d2617a204677":{
      "scriptId":"u15"},
    "793b27b633ad41fcb442a403060a33d6":{
      "scriptId":"u16"},
    "cd0499a919044b01bbe1b09c1c4fe6f9":{
      "scriptId":"u17"},
    "273aea964b604b4e827b28c584589292":{
      "scriptId":"u18"},
    "b0072b37f5b041af800193f1e9ac4b90":{
      "scriptId":"u19"},
    "4ffc493fdbea4a0d879d0a250af5750c":{
      "scriptId":"u20"},
    "6ba6cdd61948445e939cda554993d7ac":{
      "scriptId":"u21"},
    "cf6fde0668ce407e8965f9f798542264":{
      "scriptId":"u22"},
    "35c6696d9ce6418481114bda63de00be":{
      "scriptId":"u23"},
    "88e86a1c0b5840caad5aefc4a35ba6b3":{
      "scriptId":"u24"},
    "ff5d739592ff4aeda4ed7b89491f5279":{
      "scriptId":"u25"},
    "979acd319d9d4f67b204e7b8cb470366":{
      "scriptId":"u26"},
    "fc42210b9f5a4b7da0aeec540f34637f":{
      "scriptId":"u27"},
    "0627808ad76d446898935ce53c5589b7":{
      "scriptId":"u28"},
    "bb8c202c5c164a0180ebbd54bac502db":{
      "scriptId":"u29"},
    "20227359175349e0bfc5c6a1eaf10534":{
      "scriptId":"u30"},
    "4e3a9b7dc1544c0c9e068863e8c43916":{
      "scriptId":"u31"},
    "02fdd70ff16f4eedabc1183fa039071b":{
      "scriptId":"u32"},
    "4d7dd8e64ba243a5b0acbeabd69963ff":{
      "scriptId":"u33"},
    "4096ffe763e8448da76948ab70b875fc":{
      "scriptId":"u34"},
    "c12ad243293148938dd56d5706d78667":{
      "scriptId":"u35"},
    "64bdecc007ba47fb84e71dac8cf38870":{
      "scriptId":"u36"},
    "1908a25357d44cd7aedcc57bd049be7b":{
      "scriptId":"u37"},
    "9351fbe455e34740853c7ecdb1d6de01":{
      "scriptId":"u38"},
    "352da32e965648fca3a02efa6d1b2dd7":{
      "scriptId":"u39"},
    "6c9c1e2bade546b29189dea86ef6c06c":{
      "scriptId":"u40"},
    "59d9b65d1b2b4d988fa5c795d2b9659c":{
      "scriptId":"u41"},
    "88b98d09526d418b8bb652d8696bfed4":{
      "scriptId":"u42"},
    "7617a2e67ee241b9a2d332c89c8299bf":{
      "scriptId":"u43"},
    "d50bee15887548ce8ff8d53f89e2b1a1":{
      "scriptId":"u44"},
    "34e288323c1c49538306c53d4ed3325b":{
      "scriptId":"u45"},
    "5d734e7e70dd4a3e9a5dfa7b7550d512":{
      "scriptId":"u46"},
    "e2ec5f44be4d43049589eee5a9f5060f":{
      "scriptId":"u47"},
    "1f8eadadfa17462a950aa370917b02df":{
      "scriptId":"u48"},
    "62675e2f1d1d425f909f0a29612096fc":{
      "scriptId":"u49"},
    "b19ce1f5cf684068b9d43b9314131fe9":{
      "scriptId":"u50"},
    "d061b0cea7fc401ba8113f7619616399":{
      "scriptId":"u51"},
    "84781a8beae542c8a0f809219112e9db":{
      "scriptId":"u52"},
    "c7cb933f5b0544d9ae8854d3394cca38":{
      "scriptId":"u53"},
    "627fd09969cd4cbeb3835ba2ba264b74":{
      "scriptId":"u54"},
    "7a84777daf4b4529be092e8e1d5a5d2e":{
      "scriptId":"u55"},
    "096a1a16dd9e4507bb39f309d28e09a2":{
      "scriptId":"u56"},
    "b9f2fbb038c5457e8577e1bf17ae1ac6":{
      "scriptId":"u57"},
    "823b9d2ab3d84140a2bf353342e3e496":{
      "scriptId":"u58"},
    "7fe3392b840a422f8185f6dcb0ef65c2":{
      "scriptId":"u59"},
    "129d5ce9ecbe47c3a47308aedf9b2828":{
      "scriptId":"u60"},
    "b24d26c84ac64170a0527998d7f68fe2":{
      "scriptId":"u61"},
    "6968194a270e4424a97adbef6488df81":{
      "scriptId":"u62"},
    "a62d84b278734b1499f72d0e439e461d":{
      "scriptId":"u63"},
    "2cff92ad80ae4d3c94dfb4a7b7faf50f":{
      "scriptId":"u64"},
    "aec54004202a41118f880e800514e1ef":{
      "scriptId":"u65"},
    "9302e0696812472ea2f3b052f8b81cac":{
      "scriptId":"u66"},
    "31d9af566f954ca192c3232d008f0c22":{
      "scriptId":"u67"},
    "ba795135fc3b43aabd0c7c32bbf720fd":{
      "scriptId":"u68"},
    "b33f0c31044a4e028be0b44f0d053ca9":{
      "scriptId":"u69"},
    "055b8c1723c14fc59814583dee3c709c":{
      "scriptId":"u70"},
    "31caffc739a84d369be6991d61138a5e":{
      "scriptId":"u71"},
    "46c52d1cb5cc4c06a43bd788c76eb083":{
      "scriptId":"u72"},
    "d929b1497c3d4d0aa6d78c5aaf8f9c7f":{
      "scriptId":"u73"},
    "313d9739689a4dde9e51908a4e328d14":{
      "scriptId":"u74"},
    "5ce33147497943d2a9d7303da49c6e9e":{
      "scriptId":"u75"},
    "ee85ff8543174ee48758a4bdc9aa8357":{
      "scriptId":"u76"},
    "196ea582bc7743c6bf15590219dbe04c":{
      "scriptId":"u77"},
    "e14319f9f3924bef9ff20d8dc3947e6c":{
      "scriptId":"u78"},
    "3af36ddc7cd747259198af9cb60a654e":{
      "scriptId":"u79"},
    "1f6d4371a836401684d992c24db8e393":{
      "scriptId":"u80"},
    "9ee35a07ac8c43d9947e96fa15565a1a":{
      "scriptId":"u81"},
    "9c342e96ca4e435786a3911c819fb0c0":{
      "scriptId":"u82"}}});