$axure.loadCurrentPage({
  "url":"查看用户信息.html",
  "generationDate":new Date(1557073067307.35),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"66333e0ad1284cf68c3be39093f931cf",
    "type":"Axure:Page",
    "name":"查看用户信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"98241f6b71f5428cb6e5743f64a27020",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":20,
              "y":30},
            "size":{
              "width":81,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00d1db7dc16642d8bf3a63be494f64c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":20,
                  "y":30},
                "size":{
                  "width":81,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2a01bf6e6f74987b1ce49698e0724d5",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":80},
            "size":{
              "width":193,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dcace8a80914e70ab19f67a918d9704",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":97,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0dd5e8d45bb543ad9e205bbd046225e9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":97,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看用户信息/u3.png"}},
{
              "id":"e5f5fd0716194d1c88b68f2ac6a3d030",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":97,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"560d156f6b0447a987e9b7b7394a70c8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":97,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看用户信息/u3.png"}},
{
              "id":"a52608267eb043238e9436ca220bae8d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":97,
                  "y":30},
                "size":{
                  "width":96,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"44d89cbc903548aa85afcffa13f55499",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":97,
                      "y":30},
                    "size":{
                      "width":96,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看用户信息/u5.png"}},
{
              "id":"f90c17a9a8a44cf29e88932112ec2c01",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":97,
                  "y":60},
                "size":{
                  "width":96,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6d6c4c6bec0c4bf68591ee80819e0c9b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":97,
                      "y":60},
                    "size":{
                      "width":96,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看用户信息/u5.png"}},
{
              "id":"356c474e3ed04440b8476e8afec73297",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":97,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cd17c524a9b74a63aa40003e3bd21e3d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":97,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看用户信息/u3.png"}},
{
              "id":"095c69d9d5594056b9bf8e07b5eb8589",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":97,
                  "y":0},
                "size":{
                  "width":96,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"01b8f108647a41d98cfedd975f4f8972",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":97,
                      "y":0},
                    "size":{
                      "width":96,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看用户信息/u5.png"}},
{
              "id":"b0c7364b72554016ad41412e6c1ff709",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":97,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a1407fe6ba2140a5b4ca1fc44c41dc03",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":97,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看用户信息/u19.png"}},
{
              "id":"6e55bd9f507549a8bbde134d419713a2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":97,
                  "y":120},
                "size":{
                  "width":96,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a67227723e38489691c8e79e3851fc93",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":97,
                      "y":120},
                    "size":{
                      "width":96,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看用户信息/u21.png"}},
{
              "id":"e5aa6ad938e94ac89e57c3586f3d344e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":97,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9f502a09f48d45618362dc6b5503cd78",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":97,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看用户信息/u3.png"}},
{
              "id":"c90b99ba5bf844e3922a2360473934bd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":97,
                  "y":90},
                "size":{
                  "width":96,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ed1ee04ca6b541348c6628b8a8e79fbf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":97,
                      "y":90},
                    "size":{
                      "width":96,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看用户信息/u5.png"}}]},
{
          "id":"777028116fa2499591057620f84b0ee8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":255},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 学生列表",
                      "target":{
                        "targetType":"page",
                        "url":"学生列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "98241f6b71f5428cb6e5743f64a27020":{
      "scriptId":"u0"},
    "00d1db7dc16642d8bf3a63be494f64c8":{
      "scriptId":"u1"},
    "c2a01bf6e6f74987b1ce49698e0724d5":{
      "scriptId":"u2"},
    "356c474e3ed04440b8476e8afec73297":{
      "scriptId":"u3"},
    "cd17c524a9b74a63aa40003e3bd21e3d":{
      "scriptId":"u4"},
    "095c69d9d5594056b9bf8e07b5eb8589":{
      "scriptId":"u5"},
    "01b8f108647a41d98cfedd975f4f8972":{
      "scriptId":"u6"},
    "2dcace8a80914e70ab19f67a918d9704":{
      "scriptId":"u7"},
    "0dd5e8d45bb543ad9e205bbd046225e9":{
      "scriptId":"u8"},
    "a52608267eb043238e9436ca220bae8d":{
      "scriptId":"u9"},
    "44d89cbc903548aa85afcffa13f55499":{
      "scriptId":"u10"},
    "e5f5fd0716194d1c88b68f2ac6a3d030":{
      "scriptId":"u11"},
    "560d156f6b0447a987e9b7b7394a70c8":{
      "scriptId":"u12"},
    "f90c17a9a8a44cf29e88932112ec2c01":{
      "scriptId":"u13"},
    "6d6c4c6bec0c4bf68591ee80819e0c9b":{
      "scriptId":"u14"},
    "e5aa6ad938e94ac89e57c3586f3d344e":{
      "scriptId":"u15"},
    "9f502a09f48d45618362dc6b5503cd78":{
      "scriptId":"u16"},
    "c90b99ba5bf844e3922a2360473934bd":{
      "scriptId":"u17"},
    "ed1ee04ca6b541348c6628b8a8e79fbf":{
      "scriptId":"u18"},
    "b0c7364b72554016ad41412e6c1ff709":{
      "scriptId":"u19"},
    "a1407fe6ba2140a5b4ca1fc44c41dc03":{
      "scriptId":"u20"},
    "6e55bd9f507549a8bbde134d419713a2":{
      "scriptId":"u21"},
    "a67227723e38489691c8e79e3851fc93":{
      "scriptId":"u22"},
    "777028116fa2499591057620f84b0ee8":{
      "scriptId":"u23"}}});