$axure.loadCurrentPage({
  "url":"评定成绩.html",
  "generationDate":new Date(1557073067755.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7bf7cdee9c26492290f449bcd23fd645",
    "type":"Axure:Page",
    "name":"评定成绩",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ab31050ca7da4759a11e5e3ddbca58a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":50},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6887b5d0f68e4327be8e0a9c6269c4de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":50},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"375b0bacc8b34ddf8e1f8d54b4b69c94",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":57,
              "y":50},
            "size":{
              "width":153,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"ec75c589d59147da85f385d0581a0f5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":50},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b16b0df840484c5283980eea0c49e45b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":50},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7845ef2fa7004be0af5e151cbb7a5066",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":277,
              "y":50},
            "size":{
              "width":153,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"50825d2dc57940c7a11f451b6179f56f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":50},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69747bed177048ccaf76578ac23148d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":50},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0eef202dd97c4b2f87f8d7b0d2fc6afc",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":497,
              "y":50},
            "size":{
              "width":153,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"71b87526fb62468a809ba6238e39180b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":220,
              "y":109},
            "size":{
              "width":200,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"4a19ba54b14f40b6a264295d381adc58",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":57,
              "y":153},
            "size":{
              "width":517,
              "height":77}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"923df0463b0e48279ecff8c1b4bfb847",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":103,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f69507397c1e4a6da7159ff38f8abb3f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":103,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看成绩/u62.png"}},
{
              "id":"2f18bcf52cdc4df09ad9d7ad26b689e5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":103,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"177959889ec3415aa0fa32a3b4e054ee",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":103,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看成绩/u72.png"}},
{
              "id":"f02189d622aa443d98e169da02289e1d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":103,
                  "y":0},
                "size":{
                  "width":103,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5421a17b0d614258864a93d201ddbb54",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":103,
                      "y":0},
                    "size":{
                      "width":103,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看成绩/u62.png"}},
{
              "id":"57d5766119d94c98855415b6eafee25f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":103,
                  "y":30},
                "size":{
                  "width":103,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4a4c195fd40e4eef8fcad1b817c1c649",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":103,
                      "y":30},
                    "size":{
                      "width":103,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看成绩/u72.png"}},
{
              "id":"407b33fd4ab04c6da7c34796f401a8dd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":206,
                  "y":0},
                "size":{
                  "width":103,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"675c93e9620c410396f28cca740a038f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":206,
                      "y":0},
                    "size":{
                      "width":103,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看成绩/u62.png"}},
{
              "id":"c059ce98eef349b4b6f98f86fdcd7416",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":206,
                  "y":30},
                "size":{
                  "width":103,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8c69ccb8259c45139fa31ddb971723fc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":206,
                      "y":30},
                    "size":{
                      "width":103,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看成绩/u72.png"}},
{
              "id":"0da955debafd4c77abc82fe79f7825a5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":309,
                  "y":0},
                "size":{
                  "width":103,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f85a290617cd4c909efe15ae6aef6d09",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":309,
                      "y":0},
                    "size":{
                      "width":103,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看成绩/u62.png"}},
{
              "id":"69bf416a6f3c48c9b04f716d7d58845f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":309,
                  "y":30},
                "size":{
                  "width":103,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"80baf12e37b741d581b23fffd11fc624",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":309,
                      "y":30},
                    "size":{
                      "width":103,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看成绩/u72.png"}},
{
              "id":"595eec17ec5a474f87127494c729e2d4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":412,
                  "y":0},
                "size":{
                  "width":105,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"31f8df6b7d674865aec38c82e5e74ece",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":412,
                      "y":0},
                    "size":{
                      "width":105,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选择课程/u52.png"}},
{
              "id":"fc3c6795d8494dbbbe4d4df00bdb3800",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":412,
                  "y":30},
                "size":{
                  "width":105,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"13b448483d0a4c21942019014c0b41e9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":412,
                      "y":30},
                    "size":{
                      "width":105,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看成绩/u80.png"}}]},
{
          "id":"dcd98d9302314e07be8e7edd8b1242e7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":230},
            "size":{
              "width":530,
              "height":70}},
          "adaptiveStyles":{
}},
{
          "id":"5f63e4f0412c40f6ac8939520b6b3a82",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":67,
              "y":190},
            "size":{
              "width":73,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"f04da8e999e146a08820cbc212675947",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":190},
            "size":{
              "width":73,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"5109fa24e91544fda874b8ab1cb01db5",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":387,
              "y":190},
            "size":{
              "width":73,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"ab5e76f081ad47669156c62325c88d1a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":279,
              "y":190},
            "size":{
              "width":73,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"2d6a403bd1d54c95ad6bf144b731c038",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":487,
              "y":190},
            "size":{
              "width":73,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"20d75f026e60447685a763377b9bc285",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":156.5,
              "y":320},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 学生列表",
                      "target":{
                        "targetType":"page",
                        "url":"学生列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"f628640858c540bd88c224c82529a01a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":320},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 评定成绩",
                      "target":{
                        "targetType":"page",
                        "url":"评定成绩.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "ab31050ca7da4759a11e5e3ddbca58a5":{
      "scriptId":"u0"},
    "6887b5d0f68e4327be8e0a9c6269c4de":{
      "scriptId":"u1"},
    "375b0bacc8b34ddf8e1f8d54b4b69c94":{
      "scriptId":"u2"},
    "ec75c589d59147da85f385d0581a0f5b":{
      "scriptId":"u3"},
    "b16b0df840484c5283980eea0c49e45b":{
      "scriptId":"u4"},
    "7845ef2fa7004be0af5e151cbb7a5066":{
      "scriptId":"u5"},
    "50825d2dc57940c7a11f451b6179f56f":{
      "scriptId":"u6"},
    "69747bed177048ccaf76578ac23148d8":{
      "scriptId":"u7"},
    "0eef202dd97c4b2f87f8d7b0d2fc6afc":{
      "scriptId":"u8"},
    "71b87526fb62468a809ba6238e39180b":{
      "scriptId":"u9"},
    "4a19ba54b14f40b6a264295d381adc58":{
      "scriptId":"u10"},
    "923df0463b0e48279ecff8c1b4bfb847":{
      "scriptId":"u11"},
    "f69507397c1e4a6da7159ff38f8abb3f":{
      "scriptId":"u12"},
    "f02189d622aa443d98e169da02289e1d":{
      "scriptId":"u13"},
    "5421a17b0d614258864a93d201ddbb54":{
      "scriptId":"u14"},
    "407b33fd4ab04c6da7c34796f401a8dd":{
      "scriptId":"u15"},
    "675c93e9620c410396f28cca740a038f":{
      "scriptId":"u16"},
    "0da955debafd4c77abc82fe79f7825a5":{
      "scriptId":"u17"},
    "f85a290617cd4c909efe15ae6aef6d09":{
      "scriptId":"u18"},
    "595eec17ec5a474f87127494c729e2d4":{
      "scriptId":"u19"},
    "31f8df6b7d674865aec38c82e5e74ece":{
      "scriptId":"u20"},
    "2f18bcf52cdc4df09ad9d7ad26b689e5":{
      "scriptId":"u21"},
    "177959889ec3415aa0fa32a3b4e054ee":{
      "scriptId":"u22"},
    "57d5766119d94c98855415b6eafee25f":{
      "scriptId":"u23"},
    "4a4c195fd40e4eef8fcad1b817c1c649":{
      "scriptId":"u24"},
    "c059ce98eef349b4b6f98f86fdcd7416":{
      "scriptId":"u25"},
    "8c69ccb8259c45139fa31ddb971723fc":{
      "scriptId":"u26"},
    "69bf416a6f3c48c9b04f716d7d58845f":{
      "scriptId":"u27"},
    "80baf12e37b741d581b23fffd11fc624":{
      "scriptId":"u28"},
    "fc3c6795d8494dbbbe4d4df00bdb3800":{
      "scriptId":"u29"},
    "13b448483d0a4c21942019014c0b41e9":{
      "scriptId":"u30"},
    "dcd98d9302314e07be8e7edd8b1242e7":{
      "scriptId":"u31"},
    "5f63e4f0412c40f6ac8939520b6b3a82":{
      "scriptId":"u32"},
    "f04da8e999e146a08820cbc212675947":{
      "scriptId":"u33"},
    "5109fa24e91544fda874b8ab1cb01db5":{
      "scriptId":"u34"},
    "ab5e76f081ad47669156c62325c88d1a":{
      "scriptId":"u35"},
    "2d6a403bd1d54c95ad6bf144b731c038":{
      "scriptId":"u36"},
    "20d75f026e60447685a763377b9bc285":{
      "scriptId":"u37"},
    "f628640858c540bd88c224c82529a01a":{
      "scriptId":"u38"}}});