$axure.loadCurrentPage({
  "url":"登出.html",
  "generationDate":new Date(1557073067144.33),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"189a1b58d7fa42609f7ff15bd3e35da9",
    "type":"Axure:Page",
    "name":"登出",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7dbcb5f4692a42e39775041ca86e4430",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":0,
              "y":210},
            "size":{
              "width":910,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af483feb3be8400483bfd5bc02be881b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":0,
                  "y":210},
                "size":{
                  "width":910,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登出/u0.png"}},
{
          "id":"356bc20d64814badb6ec26f9d815c231",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":40},
            "size":{
              "width":910,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ea6d28b7f5b4a2eaad4af064d07907e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":910,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登出/u2.png"}},
{
          "id":"bb247bfdd5f647129e64d9101adfd395",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":55},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18dde9df82c34c989ce0c39548a6b80a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":55},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"851d23f36129463298fc25cb7c5e3341",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":140,
              "y":55},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab1e552b6f144892897e2a107d4c4e08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":140,
                  "y":55},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21c8de8be1fc4a59a6a1d5882c0260be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":270,
              "y":55},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83bc531833ef4d80891006a90c188541",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":270,
                  "y":55},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46da52403b8241fb80573979c1a8acbc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":225},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2657b8ce8af474ab680f73c51cfee86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":225},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99157a90ca134e8fa232af8030f3231b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":140,
              "y":225},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ff7cc7fc2824882820a922b0587b96d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":140,
                  "y":225},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"730e1dac895d48c6ad46be5101675975",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":270,
              "y":225},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71f1b87edcf74ed2b8b06fb8b81a0b0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":270,
                  "y":225},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8074ec7260aa4cffafbf2dddb9897561",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":210},
            "size":{
              "width":141,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7bf362f34ea40d781e1606014932c38",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":141,
                  "height":66}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c2453a5b64084967878281ca5cfa96e0",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"28px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":141,
                      "height":66}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8425ae70ac49442ab67b6f1d870c25ce",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"28px",
                        "fontWeight":"700",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":141,
                          "height":66}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登出/u18.png"}}]},
{
              "id":"98438e7225d04797a30f57a882d86d7d",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":141,
                  "height":148},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3d7cf437c8e14dfd8a2118295d917f20",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":141,
                      "height":148}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9ab2e399be40428ab09ae102676cd69b",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":141,
                          "height":37},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"6a0843bb68c545a8a7eb1ab1421b1b32",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"20px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":141,
                              "height":37},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 增加实验",
                                  "target":{
                                    "targetType":"page",
                                    "url":"增加实验.html",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/登出/u22.png"}},
{
                      "id":"0963df929eec45cd964b2ae74e7bd844",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":37},
                        "size":{
                          "width":141,
                          "height":37},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"108e3f81109d46b7a3f7fdd09062d69e",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"20px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":37},
                            "size":{
                              "width":141,
                              "height":37},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 查询实验",
                                  "target":{
                                    "targetType":"page",
                                    "url":"查询实验.html",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/登出/u22.png"}},
{
                      "id":"5862c237d8e0458db36952f7f92f30d8",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":74},
                        "size":{
                          "width":141,
                          "height":37},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"1bf46a9898b5434a9dd6956e3668d93b",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"20px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":74},
                            "size":{
                              "width":141,
                              "height":37},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 编辑实验信息",
                                  "target":{
                                    "targetType":"page",
                                    "url":"编辑实验信息.html",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/登出/u22.png"}},
{
                      "id":"1d61d0081f6248d5825711b6063f415c",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":111},
                        "size":{
                          "width":141,
                          "height":37},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"8ff2d487908c4195a266969a62887be3",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"20px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":111},
                            "size":{
                              "width":141,
                              "height":37},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 删除实验",
                                  "target":{
                                    "targetType":"page",
                                    "url":"删除实验.html",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/登出/u28.png"}}]}],
              "parentCellId":"c2453a5b64084967878281ca5cfa96e0"}]},
{
          "id":"2a972b61592e42f081063455c8188173",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":212},
            "size":{
              "width":111,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abf1ff1bb0bf4a60aa2f313937e3fa41",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":111,
                  "height":66}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a9bb2d800f5a4f8bbb97cd0f7ef4fac8",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"28px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":111,
                      "height":66}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fd32c5bbccd24b3bae87e5e33b184345",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"28px",
                        "fontWeight":"700",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":111,
                          "height":66}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登出/u32.png"}}]},
{
              "id":"36d811edc78743d79b8ada6df54ebc2e",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":111,
                  "height":98},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bf9dad9f1f2d40b2a807a9d41934adcc",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":111,
                      "height":98}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c4a9bebbc6eb469fa8863cf180633b33",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":111,
                          "height":23},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"9ce6fcae3c454e38a65432ee39286ff5",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":111,
                              "height":23},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 查看用户信息",
                                  "target":{
                                    "targetType":"page",
                                    "url":"查看用户信息.html",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/登出/u36.png"}},
{
                      "id":"c66baf813cbf4f8fba391bc038c17267",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":23},
                        "size":{
                          "width":111,
                          "height":27},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"9c6841ac122949078be1c95b6c58e826",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":23},
                            "size":{
                              "width":111,
                              "height":27},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 修改用户信息",
                                  "target":{
                                    "targetType":"page",
                                    "url":"修改用户信息.html",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/登出/u38.png"}},
{
                      "id":"90a52b17b07d49dbb6d3a80bd34c3f12",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":50},
                        "size":{
                          "width":111,
                          "height":25},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"ed7fcd6dba5946058a773d0d502570c5",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":50},
                            "size":{
                              "width":111,
                              "height":25},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 修改密码",
                                  "target":{
                                    "targetType":"page",
                                    "url":"修改密码.html",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/登出/u40.png"}},
{
                      "id":"af0ff3517b21440ab3f8437e7b27d715",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":75},
                        "size":{
                          "width":111,
                          "height":23},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"fc5ca130dbc649ccb264bd68ddac9bb9",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":75},
                            "size":{
                              "width":111,
                              "height":23},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 登录",
                                  "target":{
                                    "targetType":"page",
                                    "url":"登录.html",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/登出/u42.png"}}]}],
              "parentCellId":"a9bb2d800f5a4f8bbb97cd0f7ef4fac8"}]},
{
          "id":"4fbd560b16ad497a81c09e7fc64b55ff",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":40},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dcf524d49d74389ac9b7f179a29dc43",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"295462583bac47f38f3bc77769214c96",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"28px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2e1039b693e449d4bb81890139cf5f5b",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"28px",
                        "fontWeight":"700",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登出/u46.png"}}]},
{
              "id":"ee5c51e75283453d8be5a6aa74117521",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":92},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"060f191c608a4683a7ba3c7405acdb1e",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":100,
                      "height":92}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"65f77aff152f425584abbfe03e4fa170",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":23},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"aa0241fd9e2d461984fdb2ad06cc17ee",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":100,
                              "height":23},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 查看用户信息",
                                  "target":{
                                    "targetType":"page",
                                    "url":"查看用户信息.html",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/登出/u50.png"}},
{
                      "id":"824881cbc2a84a4dbbc5842ba9d2b94d",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":23},
                        "size":{
                          "width":100,
                          "height":23},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"8891ee7e5eb04a5484c154fe638ab9bb",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":23},
                            "size":{
                              "width":100,
                              "height":23},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 修改用户信息",
                                  "target":{
                                    "targetType":"page",
                                    "url":"修改用户信息.html",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/登出/u50.png"}},
{
                      "id":"f5f5e1c1534a4340b1ec35c0829c4e78",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":46},
                        "size":{
                          "width":100,
                          "height":23},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"46c1042a023b439f85fa37e1f18c0624",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":46},
                            "size":{
                              "width":100,
                              "height":23},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 修改密码",
                                  "target":{
                                    "targetType":"page",
                                    "url":"修改密码.html",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/登出/u50.png"}},
{
                      "id":"7009b71b9b1546b18c2ed0ed9229ea39",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":69},
                        "size":{
                          "width":100,
                          "height":23},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"899b442f4d13446c851225b9a2fcbaad",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":69},
                            "size":{
                              "width":100,
                              "height":23},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 登录",
                                  "target":{
                                    "targetType":"page",
                                    "url":"登录.html",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/登出/u56.png"}}]}],
              "parentCellId":"295462583bac47f38f3bc77769214c96"}]},
{
          "id":"c950ecbb026f4a00885ff0772f053e54",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":6},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"997d89d6221a4370ba489d488e2f041b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":6},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"212caf38a7024f5d8031dcc494818583",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":176},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17e705d64e0c48bab023cc808b0ab156",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":176},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "7dbcb5f4692a42e39775041ca86e4430":{
      "scriptId":"u0"},
    "af483feb3be8400483bfd5bc02be881b":{
      "scriptId":"u1"},
    "356bc20d64814badb6ec26f9d815c231":{
      "scriptId":"u2"},
    "0ea6d28b7f5b4a2eaad4af064d07907e":{
      "scriptId":"u3"},
    "bb247bfdd5f647129e64d9101adfd395":{
      "scriptId":"u4"},
    "18dde9df82c34c989ce0c39548a6b80a":{
      "scriptId":"u5"},
    "851d23f36129463298fc25cb7c5e3341":{
      "scriptId":"u6"},
    "ab1e552b6f144892897e2a107d4c4e08":{
      "scriptId":"u7"},
    "21c8de8be1fc4a59a6a1d5882c0260be":{
      "scriptId":"u8"},
    "83bc531833ef4d80891006a90c188541":{
      "scriptId":"u9"},
    "46da52403b8241fb80573979c1a8acbc":{
      "scriptId":"u10"},
    "e2657b8ce8af474ab680f73c51cfee86":{
      "scriptId":"u11"},
    "99157a90ca134e8fa232af8030f3231b":{
      "scriptId":"u12"},
    "3ff7cc7fc2824882820a922b0587b96d":{
      "scriptId":"u13"},
    "730e1dac895d48c6ad46be5101675975":{
      "scriptId":"u14"},
    "71f1b87edcf74ed2b8b06fb8b81a0b0d":{
      "scriptId":"u15"},
    "8074ec7260aa4cffafbf2dddb9897561":{
      "scriptId":"u16"},
    "e7bf362f34ea40d781e1606014932c38":{
      "scriptId":"u17"},
    "c2453a5b64084967878281ca5cfa96e0":{
      "scriptId":"u18"},
    "8425ae70ac49442ab67b6f1d870c25ce":{
      "scriptId":"u19"},
    "98438e7225d04797a30f57a882d86d7d":{
      "scriptId":"u20"},
    "3d7cf437c8e14dfd8a2118295d917f20":{
      "scriptId":"u21"},
    "9ab2e399be40428ab09ae102676cd69b":{
      "scriptId":"u22"},
    "6a0843bb68c545a8a7eb1ab1421b1b32":{
      "scriptId":"u23"},
    "0963df929eec45cd964b2ae74e7bd844":{
      "scriptId":"u24"},
    "108e3f81109d46b7a3f7fdd09062d69e":{
      "scriptId":"u25"},
    "5862c237d8e0458db36952f7f92f30d8":{
      "scriptId":"u26"},
    "1bf46a9898b5434a9dd6956e3668d93b":{
      "scriptId":"u27"},
    "1d61d0081f6248d5825711b6063f415c":{
      "scriptId":"u28"},
    "8ff2d487908c4195a266969a62887be3":{
      "scriptId":"u29"},
    "2a972b61592e42f081063455c8188173":{
      "scriptId":"u30"},
    "abf1ff1bb0bf4a60aa2f313937e3fa41":{
      "scriptId":"u31"},
    "a9bb2d800f5a4f8bbb97cd0f7ef4fac8":{
      "scriptId":"u32"},
    "fd32c5bbccd24b3bae87e5e33b184345":{
      "scriptId":"u33"},
    "36d811edc78743d79b8ada6df54ebc2e":{
      "scriptId":"u34"},
    "bf9dad9f1f2d40b2a807a9d41934adcc":{
      "scriptId":"u35"},
    "c4a9bebbc6eb469fa8863cf180633b33":{
      "scriptId":"u36"},
    "9ce6fcae3c454e38a65432ee39286ff5":{
      "scriptId":"u37"},
    "c66baf813cbf4f8fba391bc038c17267":{
      "scriptId":"u38"},
    "9c6841ac122949078be1c95b6c58e826":{
      "scriptId":"u39"},
    "90a52b17b07d49dbb6d3a80bd34c3f12":{
      "scriptId":"u40"},
    "ed7fcd6dba5946058a773d0d502570c5":{
      "scriptId":"u41"},
    "af0ff3517b21440ab3f8437e7b27d715":{
      "scriptId":"u42"},
    "fc5ca130dbc649ccb264bd68ddac9bb9":{
      "scriptId":"u43"},
    "4fbd560b16ad497a81c09e7fc64b55ff":{
      "scriptId":"u44"},
    "8dcf524d49d74389ac9b7f179a29dc43":{
      "scriptId":"u45"},
    "295462583bac47f38f3bc77769214c96":{
      "scriptId":"u46"},
    "2e1039b693e449d4bb81890139cf5f5b":{
      "scriptId":"u47"},
    "ee5c51e75283453d8be5a6aa74117521":{
      "scriptId":"u48"},
    "060f191c608a4683a7ba3c7405acdb1e":{
      "scriptId":"u49"},
    "65f77aff152f425584abbfe03e4fa170":{
      "scriptId":"u50"},
    "aa0241fd9e2d461984fdb2ad06cc17ee":{
      "scriptId":"u51"},
    "824881cbc2a84a4dbbc5842ba9d2b94d":{
      "scriptId":"u52"},
    "8891ee7e5eb04a5484c154fe638ab9bb":{
      "scriptId":"u53"},
    "f5f5e1c1534a4340b1ec35c0829c4e78":{
      "scriptId":"u54"},
    "46c1042a023b439f85fa37e1f18c0624":{
      "scriptId":"u55"},
    "7009b71b9b1546b18c2ed0ed9229ea39":{
      "scriptId":"u56"},
    "899b442f4d13446c851225b9a2fcbaad":{
      "scriptId":"u57"},
    "c950ecbb026f4a00885ff0772f053e54":{
      "scriptId":"u58"},
    "997d89d6221a4370ba489d488e2f041b":{
      "scriptId":"u59"},
    "212caf38a7024f5d8031dcc494818583":{
      "scriptId":"u60"},
    "17e705d64e0c48bab023cc808b0ab156":{
      "scriptId":"u61"}}});