$axure.loadCurrentPage({
  "url":"登录.html",
  "generationDate":new Date(1557073067034.81),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"51383e2fd94d452686d0f422f5c342e7",
    "type":"Axure:Page",
    "name":"登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"02d4bc2285ea4ad7816d7d422774cf03",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":107,
              "y":153},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f13650d348474fd8b5ad8923fd676428",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":107,
                  "y":153},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06d3c7723f1f4d56b4d0adab27abaac9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":107,
              "y":32},
            "size":{
              "width":623,
              "height":111}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dff9075c05224473b99e43f1d7a1de4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":107,
                  "y":32},
                "size":{
                  "width":623,
                  "height":111}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d171e4b8379749cf8454c4b531481d72",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":184,
              "y":100},
            "size":{
              "width":468,
              "height":300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29b5f70fc229473da182f1036b25d644",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":184,
                  "y":100},
                "size":{
                  "width":468,
                  "height":300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u4.png"}},
{
          "id":"d072258a7e954e7aaf7062b136077b2d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":318,
              "y":170},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"cabe3c40ed41428fb0bc0c3b01667acd",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":318,
              "y":230},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"774ce28e65c5489687121d3ce621934a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":170},
            "size":{
              "width":58,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6b29b2cdad44fbfa3449bbe73c935bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":170},
                "size":{
                  "width":58,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c638ff41a4ed4316a4baa1fd959612f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":278,
              "y":230},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1180c8f33e9742b6b12da4cfaede9f8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":278,
                  "y":230},
                "size":{
                  "width":40,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7edecfd005244aa9a1bdb217346829d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":368,
              "y":310},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 学生列表",
                      "target":{
                        "targetType":"page",
                        "url":"学生列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"d103973a10f54f9f931fa116e8db444f",
          "label":"a2",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":274},
            "size":{
              "width":82,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c68d3bdacf14e67a59965a2a4925fad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":274},
                "size":{
                  "width":82,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onCheckedChange":{
              "description":"OnCheckedChange",
              "cases":[{
                  "description":"用例 1<br> (If 选中状态值 This = 真)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":true}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 a1 = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["523a9c226ce64e36a710bf6d40c1162e"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}}},
{
          "id":"523a9c226ce64e36a710bf6d40c1162e",
          "label":"a1",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":318,
              "y":274},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68918d88d1dd4eb5bc8c16e1d9d5a762",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":318,
                  "y":274},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onCheckedChange":{
              "description":"OnCheckedChange",
              "cases":[{
                  "description":"用例 1<br> (If 选中状态值 This = 真)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":true}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 a2 = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["d103973a10f54f9f931fa116e8db444f"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}}}]}},
  "masters":{
},
  "objectPaths":{
    "02d4bc2285ea4ad7816d7d422774cf03":{
      "scriptId":"u0"},
    "f13650d348474fd8b5ad8923fd676428":{
      "scriptId":"u1"},
    "06d3c7723f1f4d56b4d0adab27abaac9":{
      "scriptId":"u2"},
    "dff9075c05224473b99e43f1d7a1de4d":{
      "scriptId":"u3"},
    "d171e4b8379749cf8454c4b531481d72":{
      "scriptId":"u4"},
    "29b5f70fc229473da182f1036b25d644":{
      "scriptId":"u5"},
    "d072258a7e954e7aaf7062b136077b2d":{
      "scriptId":"u6"},
    "cabe3c40ed41428fb0bc0c3b01667acd":{
      "scriptId":"u7"},
    "774ce28e65c5489687121d3ce621934a":{
      "scriptId":"u8"},
    "c6b29b2cdad44fbfa3449bbe73c935bb":{
      "scriptId":"u9"},
    "c638ff41a4ed4316a4baa1fd959612f3":{
      "scriptId":"u10"},
    "1180c8f33e9742b6b12da4cfaede9f8b":{
      "scriptId":"u11"},
    "a7edecfd005244aa9a1bdb217346829d":{
      "scriptId":"u12"},
    "d103973a10f54f9f931fa116e8db444f":{
      "scriptId":"u13"},
    "5c68d3bdacf14e67a59965a2a4925fad":{
      "scriptId":"u14"},
    "523a9c226ce64e36a710bf6d40c1162e":{
      "scriptId":"u15"},
    "68918d88d1dd4eb5bc8c16e1d9d5a762":{
      "scriptId":"u16"}}});