$axure.loadCurrentPage({
  "url":"查询课程.html",
  "generationDate":new Date(1557073067337.85),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d9daa6e5a54b4b6faf8ce2bdaba48532",
    "type":"Axure:Page",
    "name":"查询课程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"691a00e9f4d642fa91004f26959f55a0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":45},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"89a8257690a445aa8bfa2c9dd9f09086",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":45},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b8e89289038f4ac39bc0dc10889d284f",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":100},
            "size":{
              "width":427,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbf6269ddc044e5cb46977650b04d8f2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":107,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"319ad87839f44cb6ab7548ed6a5166a3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":107,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询课程/u3.png"}},
{
              "id":"9b65eca6f9324a62bb6a7920cf64c265",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":107,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cbc557b6540b4910b640cdc3ea4addc5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":107,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询课程/u3.png"}},
{
              "id":"c3f5f4c707944eb3bb517a3c68cad6b6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":107,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"09e388b2cc8f4719bab7494976396e0a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":107,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询课程/u19.png"}},
{
              "id":"46b3409e6a874af7a1668003ac8e79c5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":107,
                  "y":0},
                "size":{
                  "width":107,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"90aa3ba5c14d4c7381a13faa8cf25bd6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":107,
                      "y":0},
                    "size":{
                      "width":107,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询课程/u3.png"}},
{
              "id":"0b6f6467d8ee49628209bb1cafd0a2d4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":107,
                  "y":30},
                "size":{
                  "width":107,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"286bf40d0a1348f58590b969edf41a48",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":107,
                      "y":30},
                    "size":{
                      "width":107,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询课程/u3.png"}},
{
              "id":"3cbe1bac4a144606b962bf2692586a12",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":107,
                  "y":60},
                "size":{
                  "width":107,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cbd11566dc5747a982c0abe163028d93",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":107,
                      "y":60},
                    "size":{
                      "width":107,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询课程/u19.png"}},
{
              "id":"fd965cad1b3d4d808571d3da82c7d204",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":214,
                  "y":0},
                "size":{
                  "width":107,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c01f659746ac4cff980c10d9bda624c5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":214,
                      "y":0},
                    "size":{
                      "width":107,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询课程/u3.png"}},
{
              "id":"71c01a6ac60f4c95b802a23ebb5ace78",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":214,
                  "y":30},
                "size":{
                  "width":107,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c8857cd6d769470c8f8b4b61d05548ad",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":214,
                      "y":30},
                    "size":{
                      "width":107,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询课程/u3.png"}},
{
              "id":"e2419089bf5047a4ad92718a20b883f0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":214,
                  "y":60},
                "size":{
                  "width":107,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ab07855c97c7452ba4aecd4ebb91ca3e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":214,
                      "y":60},
                    "size":{
                      "width":107,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询课程/u19.png"}},
{
              "id":"3c01f6285af14b5192794bdf27c4e085",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":321,
                  "y":0},
                "size":{
                  "width":106,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1c31f5ebd72349a69f32fb94fa172ebf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":321,
                      "y":0},
                    "size":{
                      "width":106,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询课程/u9.png"}},
{
              "id":"7c3279f6290f48389bf0361314cbb537",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":321,
                  "y":30},
                "size":{
                  "width":106,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d7a4b90bda714b9498e11c43217b092c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":321,
                      "y":30},
                    "size":{
                      "width":106,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询课程/u9.png"}},
{
              "id":"282ca87e77cf4e60ae558da0045d418d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":321,
                  "y":60},
                "size":{
                  "width":106,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"54014daee6384e08beef591c2245854e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":321,
                      "y":60},
                    "size":{
                      "width":106,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查询课程/u25.png"}}]},
{
          "id":"198f3b609792488a87dd7dea68cc97c2",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":377,
              "y":132},
            "size":{
              "width":93,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "691a00e9f4d642fa91004f26959f55a0":{
      "scriptId":"u0"},
    "89a8257690a445aa8bfa2c9dd9f09086":{
      "scriptId":"u1"},
    "b8e89289038f4ac39bc0dc10889d284f":{
      "scriptId":"u2"},
    "fbf6269ddc044e5cb46977650b04d8f2":{
      "scriptId":"u3"},
    "319ad87839f44cb6ab7548ed6a5166a3":{
      "scriptId":"u4"},
    "46b3409e6a874af7a1668003ac8e79c5":{
      "scriptId":"u5"},
    "90aa3ba5c14d4c7381a13faa8cf25bd6":{
      "scriptId":"u6"},
    "fd965cad1b3d4d808571d3da82c7d204":{
      "scriptId":"u7"},
    "c01f659746ac4cff980c10d9bda624c5":{
      "scriptId":"u8"},
    "3c01f6285af14b5192794bdf27c4e085":{
      "scriptId":"u9"},
    "1c31f5ebd72349a69f32fb94fa172ebf":{
      "scriptId":"u10"},
    "9b65eca6f9324a62bb6a7920cf64c265":{
      "scriptId":"u11"},
    "cbc557b6540b4910b640cdc3ea4addc5":{
      "scriptId":"u12"},
    "0b6f6467d8ee49628209bb1cafd0a2d4":{
      "scriptId":"u13"},
    "286bf40d0a1348f58590b969edf41a48":{
      "scriptId":"u14"},
    "71c01a6ac60f4c95b802a23ebb5ace78":{
      "scriptId":"u15"},
    "c8857cd6d769470c8f8b4b61d05548ad":{
      "scriptId":"u16"},
    "7c3279f6290f48389bf0361314cbb537":{
      "scriptId":"u17"},
    "d7a4b90bda714b9498e11c43217b092c":{
      "scriptId":"u18"},
    "c3f5f4c707944eb3bb517a3c68cad6b6":{
      "scriptId":"u19"},
    "09e388b2cc8f4719bab7494976396e0a":{
      "scriptId":"u20"},
    "3cbe1bac4a144606b962bf2692586a12":{
      "scriptId":"u21"},
    "cbd11566dc5747a982c0abe163028d93":{
      "scriptId":"u22"},
    "e2419089bf5047a4ad92718a20b883f0":{
      "scriptId":"u23"},
    "ab07855c97c7452ba4aecd4ebb91ca3e":{
      "scriptId":"u24"},
    "282ca87e77cf4e60ae558da0045d418d":{
      "scriptId":"u25"},
    "54014daee6384e08beef591c2245854e":{
      "scriptId":"u26"},
    "198f3b609792488a87dd7dea68cc97c2":{
      "scriptId":"u27"}}});